### PR TITLE
Fix navigation bar

### LINKED ISSUE #45: 🛠 Fix navigation bar
**Type**: client

**FOF**: 1

## Description
- We want to fix the navbar to match the designs on Figma

## Screenshot
image
image

## Todo

- [ ] Refactor the navigation bar
  - You'll be working with the `<Header />` component 
  - https://github.com/ClearPathNYC/clearpath-web/blob/dev/src/components/organization-layout/header/index.tsx
- [ ] Make the navbar mobile responsive 

## Links

- [Figma](https://www.figma.com/file/qELi7Tz3K4XxXQmCVrrpRE/Clear-Path-x-H4I?node-id=1%3A2&t=wnmmIblE2fpTrpNM-0)
- [Styled Components Tips](https://javascript.plainenglish.io/react-7-tricks-to-work-with-styled-components-20eb155934b1)

## Learnings
- Navigation bar!

### PR DESCRIPTION
**Pull request by AaronAlexander-debug**
## Status:

:construction: In development

## Summary

Fixed the navbar on the organization dashboard to be more in line with the Figma.
Fixes #45

### CODE REVIEW

File: src/components/main-layout/header/index.tsx
Comment (ayanmallik) [inline src/components/main-layout/header/index.tsx:1]: Let's undo all the changes to file within `main-layout` since we only want to update the header under `organization-layout`

I think the easiest way to go about this is by copying over the original code for these files (`index.tsx`, `styles.ts`, ...) so that the file diff goes aways 💨

File: src/components/organization-layout/header/styles.ts [hunk 1]
```diff
@@ -4,23 +4,79 @@ import { device } from "utils/device";
...
-  flex-direction: column;
-  justify-content: space-between;
-  align-items: left;
-  height: 80px;
+  justify-content: left;
+  align-items: center;
+  min-height: 40px;
+  height: 100px;
+  background-color: ${(p) => p.theme.colors.bg.main};
+  padding: 0 5%;
```
Comment (ayanmallik) [inline src/components/organization-layout/header/styles.ts:12]: Let's fix this padding to be defined using pixels - we want the outside of the header to always align with the outside of the main content as shown below:

image

File: src/components/organization-layout/header/index.tsx [hunk 2]
```diff
@@ -33,9 +33,20 @@ export const Header = () => {
     <HeaderContainer>
       <NavBar>
         <ClearpathLogo size={isMobile ? "small" : "big"} />
-        <ProfileLink to="/organization/profile">
-          <IconButton icon="user" />
-        </ProfileLink>
+        {!isMobile ? (
```
Comment (ayanmallik) [inline src/components/organization-layout/header/index.tsx:36]: Great support for mobile responsiveness - looks super clean on my phone! ☎️

File: src/pages/main/academic-development/index.tsx
Comment (ayanmallik) [inline src/pages/main/academic-development/index.tsx:1]: Let's also undo any changes to this file since it seems like this code was more exploratory for the toast integration feature 🍞

**Review by ayanmallik — CHANGES_REQUESTED** [review]
Great work Aaron - really appreciate how you catered to both mobile/desktop designs while redesigning the outdated header!

Let's remove all the unnecessary file differences, fix the padding issue with the percentages, and then we should be good to merge this in! 🚀
